environment:
  matrix:
    - JOB: "3.6 32-bit"
      PYTHON_HOME: "C:\\Python36"
      TOXENV: "py36-cov"
      TOXPYTHON: "C:\\Python36\\python.exe"

    - JOB: "3.6 64-bit"
      PYTHON_HOME: "C:\\Python36-x64"
      TOXENV: "py36-cov"
      TOXPYTHON: "C:\\Python36-x64\\python.exe"

    - JOB: "3.7 32-bit"
      PYTHON_HOME: "C:\\Python37"
      TOXENV: "py37-cov"
      TOXPYTHON: "C:\\Python37\\python.exe"

    - JOB: "3.7 64-bit"
      PYTHON_HOME: "C:\\Python37-x64"
      TOXENV: "py37-cov"
      TOXPYTHON: "C:\\Python37-x64\\python.exe"

# Do not build feature branches with open Pull Requests after the initial
# opening of a PR.
skip_branch_with_pr: true

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }

  # Prepend Python to the PATH of this build
  - "SET PATH=%PYTHON_HOME%;%PYTHON_HOME%\\Scripts;%PATH%"

  # check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # upgrade pip to avoid out-of-date warnings
  - "python -m pip install --disable-pip-version-check --user --upgrade pip"
  - "python -m pip --version"

  # install the dependencies to run the tests
  - "python -m pip install -r dev-requirements.txt"


build: false

test_script:
  - "tox"
